apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace : flask-app
spec:
  containers:
    - name: flask-container
      image: trainwithshubham/github-actions-app:latest
      ports:
        - containerPort: 80 
